name: CI

on:
  push:
  pull_request:

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: "3.13"
      - run: uv sync --group test --extra sqlite
      - run: uv run pytest --cov --cov-report=xml
      - name: Post coverage comment
        uses: MishaKav/pytest-coverage-comment@fd9adbdca9fdfbe2b9bfa44a7340e6a83346ce6c # v1.10.0
        if: github.event_name == 'pull_request'
        with:
          pytest-xml-coverage-path: coverage.xml
